import {StyleSheet} from 'react-native';
import {colors} from './variables';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

const componentStyles = StyleSheet.create({
  primaryButton: {
    paddingHorizontal: 28,
    paddingVertical: 20,
    borderColor: colors.primary,
    borderWidth: 2,
    borderRadius: 30,
    alignItems: 'center',
    minWidth: 280,
    maxWidth: 350,
    width: '100%',
  },
  secondaryButton: {
    paddingHorizontal: 28,
    paddingVertical: 20,
    borderRadius: 30,
    backgroundColor: colors.primary,
    alignItems: 'center',
    minWidth: 280,
    maxWidth: 350,
    width: '100%',
  },
  terciaryButton: {
    paddingHorizontal: 28,
    paddingVertical: 20,
    borderRadius: 30,
    alignItems: 'center',
    minWidth: 200,
    maxWidth: 350,
    width: '100%',
  },
  whiteButton: {
    paddingHorizontal: 28,
    paddingVertical: 20,
    backgroundColor: colors.secondary,
    borderRadius: 30,
    alignItems: 'center',
    minWidth: 280,
    maxWidth: 350,
    width: '100%',
  },
  loadingContainer: {
    width: '100%',
    height: '100%',
    backgroundColor: colors.secondary,
    justifyContent: 'center',
  },
  mainContainer: {
    width: '100%',
    height: '100%',
    paddingBottom: 50,
  },
  headerContainer: {
    width: '100%',
    height: 90,
    backgroundColor: colors.secondary,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 30,
    alignItems: 'center',
  },
  cardContainer: {
    backgroundColor: colors.secondary,
    width: '100%',
    borderTopStartRadius: 20,
    borderTopEndRadius: 20,
    overflow: 'hidden',
    paddingTop: 50,
    paddingBottom: 170,
    flex: 1,
  },
  sectionOptions: {
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    width: '100%',
    marginBottom: 14,
  },
  imageContainer: {
    width: '100%',
    height: 180,
    borderRadius: 20,
  },
  imageContainerLarge: {
    width: '100%',
    height: 250,
    borderRadius: 20,
    overflow: 'hidden',
  },
  imageFormat: {
    width: '100%',
    height: '100%',
    overflow: 'hidden',
    borderRadius: 20,
    position: 'relative',
  },
  imageFormatAlt: {
    width: '100%',
    height: '100%',
    overflow: 'hidden',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    position: 'relative',
  },
  imageDescription: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.quaternary,
    overflow: 'hidden',
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  imageTitle: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.quaternary,
    overflow: 'hidden',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  cardThumbnailPosition: {
    position: 'absolute',
    top: 25,
    left: 40,
  },
  cardThumbnailPositionRight: {
    position: 'absolute',
    top: 25,
    right: 20,
  },
  cardThumbnailCentral: {
    position: 'absolute',
    top: 0,
    left: 0,
    right:0,
    bottom:0,
    alignItems: 'center', 
    justifyContent:'center'
  },
  cardThumbnailPill: {
    borderRadius: 14,
    textTransform: 'uppercase',
    paddingVertical: 6,
    paddingHorizontal: 12,
    minWidth: 103,
    textAlign: 'center',
  },
  bottomLableFont: {
    fontFamily: 'Anton',
    fontWeight: '400',
    fontSize: 14,
    textTransform: 'uppercase',
  },
  drawerStyle: {
    width: '100%',
    backgroundColor: colors.secondary,
  },
  modalOverlay: {
    position: 'absolute',
    height: '100%',
    width: '100%',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.terciary,
    overflow: 'hidden',
  },
  modalView: {
    backgroundColor: colors.backdrop,
  },
  qrModalContainer: {
    width: '100%',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 44,
    paddingHorizontal: 60,
    paddingBottom: 36,
    overflow: 'hidden',
    backgroundColor: colors.quaternary,
  },
  QRContainer: {
    backgroundColor: colors.lightGray,
    position: 'relative',
    padding: 23,
    marginBottom: 13,
    alignItems: 'center',
    borderRadius: 10,
  },
  QRFormat: {
    height: 171,
    width: 171,
  },
  CheckIcon: {
    height: 71,
    width: 71,
  },
  IconSizeRegular: {
    height: 35,
  },
  IconSizeLarge: {
    height: 41,
  },
  backDrop: {
    backgroundColor: colors.backdrop,
    flex: 1,
    zIndex: 10,
    height: hp(100),
  },
  backDropBlack: {
    backgroundColor: colors.black,
    flex: 1,
  },
  grayLine: {
    width: '100%',
    borderBottomWidth: 1,
    borderColor: colors.lightGray,
  },
  blackLine: {
    width: '100%',
    borderBottomWidth: 1,
    borderColor: colors.primary,
  },
  blackLineDanger: {
    width: '100%',
    borderBottomWidth: 1,
    borderColor: colors.danger,
  },
  switchSize: {
    transform: [{scaleX: 1.2}, {scaleY: 1.2}],
  },
  popupContainer: {
    width: 330,
    borderRadius: 20,
    overflow: 'hidden',
  },
  recoveryCodeContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recoveryCodeInput: {
    position: 'absolute',
    height: 0,
    width: 0,
    opacity: 0,
  },
  CodeInputContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hiddenCodeInput: {
    position: 'absolute',
    height: 0,
    width: 0,
    opacity: 0,
  },
  inputsContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  inputContainer: {
    borderRadius: 10,
    height: 67,
    width: 67,
    backgroundColor: colors.lightGrayAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputContainerFocused: {
    borderColor: colors.terciary,
    borderWidth: 1,
  },
  filledInput: {
    backgroundColor: colors.terciaryLighter,
  },
  carouselButton: {
    borderColor: colors.primary,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 32,
    paddingVertical: 5,
    marginEnd: 10,
  },
  navigationContainer: {
    backgroundColor: colors.primary,
    position: 'absolute',
    justifyContent: 'center',
    bottom: 23,
    left: wp('5%'),
    right: wp('5%'),
    height: hp('9.83%'),
    borderRadius: 20,
    borderTopWidth: 0,
    alignContent: 'center',
    paddingHorizontal: 0,
    paddingStart: 0,
    paddingEnd: 10,
  },
  bottomNavigatorItem: {
    alignItems: 'center',
    maxWidth: 300,
    margin: 0,
    padding: 0,
    width: '100%',
    paddingHorizontal: 0,
    marginHorizontal: 0,
  },
  qrInput: {borderRadius: 20, paddingHorizontal: 10, minHeight: 60},
});

export default componentStyles;
